[project]
name = "discord-influencer-follower-bot"
version = "0.1.0"
authors = [{ name = "Amadej Kastelic", email = "amadejkastelic7@gmail.com" }]

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
skip-string-normalization = true
